/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    // TODO implement
    public String menu() {
        return "";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
